### ISSUE TITLE
Github Actions don't set response.headers['Authorization'] correctly

### ISSUE THREAD

**Issue by davidwparker** [waiting-for-dev/devise-jwt#203]
## Expected behavior
```ruby
    response.headers['Authorization']
```

Should be the Authorization header.

(can also use `request.env['warden-jwt_auth.token']` which also doesn't work).

## Actual behavior

```ruby
    response.headers['Authorization']
```
is set to `***`.

Everything works fine if run locally. However, when running on Github Actions, it sets the incorrect thing.

## Steps to Reproduce the Problem

1. Use rspec my request specs on Github Actions results in `***` instead of the `Bearer {JWT}`

## Debugging information

Provide following information. Please, format pasted output as code. Feel free to remove the secret key value.

- Version of `devise-jwt` in use
    devise-jwt (0.8.0)

- Version of `rails` in use
6.1.1

- Version of `warden-jwt_auth` in use
    warden-jwt_auth (0.5.0)

Sorry if this isn't the proper place to ask this, but it's really hard to Google or Github search for `"***"`.

I've searched all the files in this repo as well as the warden one, and couldn't find `***`.

I'm at a loss for how to run these specs in Github Actions. Thanks!

If needed, can update my repo and output more things like what you have below.

- Output of `Devise::JWT.config`
- Output of `Warden::JWTAuth.config`
- Output of `Devise.mappings`
- If your issue is related with not getting a JWT from the server:
  - Involved request path, method and request headers
  - Response headers for that request

**Comment by waiting-for-dev** [comment]
It looks like your setup is masking sensitive information from the logs. I haven't had the chance to use GH actions yet, but there's an [add_mask](https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#masking-a-value-in-log) command which looks like the responsible. I don't think you have an issue here, as it only should affect what you see in the logs but not the actual test data. So, if your tests are failing it's for some other reason with the actual data. Definitely, it's not an issue from our end.

**Comment by davidwparker** [comment]
Here's my workflow for GH actions:

```yml
env:
  RUBY_VERSION: 3.0.0
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: test_db
  STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
  TEST_ENV_NUMBER: 1

name: Rails Specs
on: [push,pull_request]
jobs:
  rspec-test:
    name: RSpec
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgres:latest
        ports:
        - 5432:5432
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Install postgres client
        run: sudo apt-get install libpq-dev
      - name: Install dependencies
        run: |
          gem install bundler
          bundler install
      - name: Create database
        run: |
          bundler exec rails db:create RAILS_ENV=test
          bundler exec rails db:migrate RAILS_ENV=test
      - name: Run tests
        run: bundler exec rspec spec/requests/projects*
      - name: Upload coverage results
        uses: actions/upload-artifact@master
        if: always()
        with:
          name: coverage-report
          path: coverage
```

It doesn't seem to have anything about masking, but that seems like it's a good starting point to look. I'll investigate it and let you know what I end up finding out. My hunch is you're correct but maybe it's hidden by default.
